### ISSUE TITLE
Questions regarding padding batch and reorder session

### ISSUE THREAD

**Issue by chijames** [LayneIns/E2E-dialo-disentanglement#1]
Hi,

Thanks for releasing the code!
I have several questions. 1. What is the purpose for ln 113 to 119 in utils.py? Seems like you are appending several empty rows to the utterance matrix. 2. Is this related to the reorder_session function? Specifically, I cannot get the point of using reverse_dict and transpose_matrix.

Thanks!

**Comment by LayneIns** [comment]
@chijames Hi, Thanks for your interests in our work. 

1.
Line 113 to 119 aim to pad a dialogue. Notice that each dialogue consists of m utterances and for the i<sup>th</sup> utterance, it contains n<sub>i</sub> tokens. We have to pad the dialogue to m<sub>max</sub> utterances and each utterance to n<sub>max</sub> tokens.

2.
Yes it is. The goal of transpose_matrix is to make the utterances in one session together. For example, the original utterance labels are [0,0, 1, 0, 1, 1, 0, 1]. We have to make them as [0, 0, 0, 0, 1, 1, 1, 1] and then cut them as [[0, 0, 0, 0], [1, 1, 1, 1]] to get all the session states. Otherwise we cannot use the LSTM to get the representations.

A suggestion is to firstly read the model part. We adopt the training idea in dependency parsing by pre-calculating all the hidden states. 

If you have any other questions, please leave a comment.

Thanks!

**Comment by chijames** [comment]
Thanks for the reply!
